### ISSUE TITLE
RFE: Ability to zoom into a specific chapter.

### ISSUE THREAD

**Issue by xsgordon** [jwulf/press-star#31]
When working on a large guide in the star I would like to be able to "zoom" such that instead of seeing the entire guide with edit links I can just look at a specific part/chapter I am working on (at least temporarily). Possibly through the use of collapse all/expand all buttons or something like that?

**Comment by jwulf** [comment]
You know about the pop-up "TOC Anywhere" from Publican Website to allow the author to quickly teleport anywhere in the book from anywhere? It's at the bottom of the screen and pops up on click.

Obviously the screen limits what you can see at once. Do you want "white space" around the part you are working on, so that the words from outside that section don't push themselves into your consciousness?

**Comment by xsgordon** [comment]
I know about the TOC, but much like on a "real" publican website viewing the full html-single output it is quite unwieldy to work with for large guides. What I am after is the ability to concentrate on a specific part/chapter/section I am working on and hide all content outside of this area.

**Comment by jwulf** [comment]
The new Zen mode button is available at every chapter / section / topic level. Click the Zen mode button to eliminate everything outside that container. Click any zen mode button again to turn the zen mode off.

Let me know how this works for you.
