### ISSUE TITLE
Tab Indentation for PDF

### ISSUE THREAD

**Issue by slong9** [jwulf/press-star#33]
It looks like pdf creation can't handle tab indentation. It works fine on HTML, but comes out a bit mangled on PDF. Deceptive since it looks great in the editor.

**Comment by jwulf** [comment]
Can I get a URL or steps to reproduce so that I can see what you are looking at.

**Comment by jwulf** [comment]
"In a &lt;screen&gt; tag, tabs are not preserved in pdf output. To reproduce:
1.  observe the tabs in the <screen> tag in topic 16078.
2. Build Content Spec ID 15807 using "csprocessor assemble 15807"
3. Observe the pdf output
4. Tabs are not preserved in the pdf output

**Comment by jwulf** [comment]
![screen shot 2013-06-03 at 7 04 45 pm](https://f.cloud.github.com/assets/406975/598431/b8efb2b8-cc2c-11e2-8cdc-03f7a6fc09e3.png)

Tabs in PDF ^

Tab depth is 2 spaces.

Tabs in HTML Preview. Tab depth is 4 or 8 spaces.

![screen shot 2013-06-03 at 7 05 01 pm](https://f.cloud.github.com/assets/406975/598434/cfbc0d02-cc2c-11e2-9abd-4e78e274ef3c.png)

To get deeper tabs in the PDF, I would suggest using spaces instead of tabs - i.e: instead of pressing the Tab key, hit the space key four or eight times to get consistent tabs.
